context("test-sampleParamFromUncertainty")

# TEST 1 ----
test_that("Detecting discrepancies in samples from the parameter uncertainty distribution", {

  set.seed(1)
  fileXLS <- system.file("extdata", "PKparametersNewFormat.xlsx", package = "MMVmalaria")

  spec <- IQRtools:::specifyParamSampling(fileXLS)

  Npop   <- 500
  Ntests <- 10

  testSample     <- IQRtools:::sampleParamFromUncertainty(spec, Npop = Npop * Ntests)
  targetMuNormal <- unlist(IQRtools:::transformParamToNormal(spec,
                                                            IQRtools:::getParamEstimates(spec))[1, IQRtools:::getNamesAllParameters(spec)])
  targetSigmaNormal <- IQRtools:::getCovMatrixUncertainty(spec)
  targetSample      <- IQRtools:::untransformParamFromNormal(spec,
                                                            as.data.frame(mvtnorm::rmvnorm(Npop * Ntests, mean = targetMuNormal,
                                                                                           sigma = targetSigmaNormal)))
  discr <- IQRtools:::detectSampleDiscrepancy(
    spec = spec,
    testSample = testSample,
    targetSample = targetSample,
    targetMuNormal = targetMuNormal,
    targetSigmaNormal = targetSigmaNormal,
    Npop = Npop, Ntests = Ntests)

  expect_true(all(sapply(discr$detectedSingleParams, startsWith, "corr")))

  # cowplot::plot_grid(plotlist = discr$listHistogramsDetectedSingleParams)
})


# TEST 2 ----
test_that("No discrepancies between samples from uncertainty generated by sampleIQRnlmeProject and sampleParamFromUncertainty.", {

  nlmeProjectPath <- system.file("extdata", "IQRtoolsExampleProject", package = "MMVmalaria")
  fileXLS <- system.file("extdata/IQRtoolsExampleProject/PKModelCovariance.xlsx", package = "MMVmalaria")

  xls <- IQRtools::generate_GPFFromIQRnlmeProject(projectPath = nlmeProjectPath,
                                                  filename    = fileXLS)

  Npop   <- 500
  Ntests <- 10

  targetSampleUncertainty <- IQRtools::sample_IQRnlmeProject(nlmeProjectPath, Nsamples = Npop * Ntests, FLAG_SAMPLE = 2)
  discrUncertainty <- IQRtools:::detectSampleDiscrepancy(
    fileXLS,
    testSample = IQRtools:::sampleParamFromUncertainty(fileXLS, Npop = Npop * Ntests),
    targetSample = targetSampleUncertainty$popParamValues,
    Npop = Npop, Ntests = Ntests,
    FLAGverbose = TRUE
  )

  expect_true(length(discrUncertainty$detectedSingleParams) == 0 &&
                length(discrUncertainty$detectedPairParams) == 0)

})


# TEST 3 ----
test_that("No discrepancy between the samples from IIV generated sampleIQRnlmeProject and sampleParamFromUncertainty", {
  nlmeProjectPath <- system.file("extdata", "IQRtoolsExampleProject", package = "MMVmalaria")
  fileXLS <- system.file("extdata/IQRtoolsExampleProject/PKModelCovariance.xlsx", package = "MMVmalaria")

  xls <- IQRtools::generate_GPFFromIQRnlmeProject(projectPath = nlmeProjectPath,
                                                  filename    = fileXLS)


  Npop   <- 500
  Ntests <- 10

  # generate a sample from IIV using the old implementation
  targetSampleIIV <- IQRtools::sample_IQRnlmeProject(nlmeProjectPath, Nsamples = Npop * Ntests, FLAG_SAMPLE = 5)

  estimates <- IQRtools:::getParamEstimates(fileXLS)
  # sample random effects using the new sampling API:
  rEffects <- IQRtools:::sampleRandomEffects(fileXLS, estimates, Nsamples = Npop * Ntests)
  # calculate individual parameter values:
  indParams <- IQRtools:::calcIndParamValues(fileXLS,
                                  estimates[rep(1, Npop * Ntests), IQRtools:::getNamesModelParameters(fileXLS)],
                                  rEffects[, IQRtools:::getNamesModelParameters(fileXLS)])

  discrIIV <- IQRtools:::detectSampleDiscrepancy(
    fileXLS,

    testSample = indParams,
    targetSample = targetSampleIIV$indParamValues,

    targetMuNormal = unlist(IQRtools:::transformParamToNormal(fileXLS, estimates))[IQRtools:::getNamesModelParameters(fileXLS)],
    targetSigmaNormal = IQRtools:::getCovMatrixIIV(fileXLS),

    Npop = Npop, Ntests = Ntests, tAlpha = 0.01)

  expect_true(length(discrIIV$detectedSingleParams) == 0 &&
                length(discrIIV$detectedPairParams) == 0)
})


