#' cureModelSnippets
#' 
#' What the function should do:
#' Based on the selected modeltype it should return the corresponding model equations for the 
#' * Model without cure
#' * The model with cure
#' in a way that they can directly be copied to the structural model. 
#'
#' @param modeltype the chosen model structure from the list of supported models, 
#' may be one of the following strings:
# "Mono Emax", "Mono Clearance Emax", "Dual Combo Emax", 
# "Dual Combo Hybrid Emax Clearance", "Triple Combo Emax", 
# "Triple Combo Hybrid Emax Clearance"
#'
#' @return the function is meant to be used interactively and does not return any object, the output will be displayed in the console
#'
#' @examples 
#' cureModelSnippets(modeltype = "Mono Emax")
cureModelSnippets <- function(modeltype = "Mono Emax") {
  
# Supported models
  models <- c("Mono Emax", "Mono Clearance Emax", 
              "Dual Combo Emax", "Dual Combo Hybrid Emax Clearance", #"Dual Combo Emax Clearance", 
              "Triple Combo Emax", "Triple Combo Hybrid Emax Clearance") #"..." 
  # Model equations without cure   
  nonCure <- case_when(modeltype == "Mono Emax" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate, and may be either a linear or nonlinear function of the drug concentration",
                           "d/dt(PL) = GR - Kkill",
                           "PL(0) = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0           # The time of the first observation relative to the time of the first dose (hours)",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Mono Clearance Emax" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate, and may be either a linear or nonlinear function of the drug concentration",
                           "d/dt(PLtot) = (GR + CLPara)*exp(PLliv-PLtot) - CLPara",
                           "d/dt(PLliv) = GR - Kkill",
                           "PLtot(0)    = PLbase + GR*Tobs0",
                           "PLliv(0)    = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase  = 0           # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0   = 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Dual Combo Emax" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PL) = GR - Kkill",
                           "PL(0) = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma   = 1          # Bliss independence interaction parameter (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Minimum Effect:",
                           "frac    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin = frac*EMAXx1 + (1-frac)*EMAXx2",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkill   = Kkillx1 + Kkillx2 - Gamma*Effx1*Effx2*KillMin",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Dual Combo Hybrid Emax Clearance" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PLtot) = (GR - Kkill + Kkillx1 + CLPara)*exp(PLliv-PLtot) - CLPara",
                           "d/dt(PLliv) = GR - Kkill",
                           "PLtot(0)    = PLbase + GR*Tobs0",
                           "PLliv(0)    = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma   = 1          # Bliss independence interaction parameter (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Minimum Effect:",
                           "frac    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin = frac*EMAXx1 + (1-frac)*EMAXx2",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkill   = Kkillx1 + Kkillx2 - Gamma*Effx1*Effx2*KillMin",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Triple Combo Emax" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PL) = GR - Kkill",
                           "PL(0) = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- Drug 3 ---",
                           "EMAXx3  = 0.10       # Maximum clearance rate Drug3 (1/hour)",
                           "EC50x3  = 0.10       # Concentration achieving 50percent of maximum effect Drug3 (ug/mL)",
                           "hillx3  = 1          # Hill coefficient Drug3 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma12   = 1          # Bliss independence interaction parameter, drug x1 and x2 (-)",
                           "Gamma13   = 1          # Bliss independence interaction parameter, drug x1 and x3 (-)",
                           "Gamma23   = 1          # Bliss independence interaction parameter, drug x2 and x3 (-)",
                           "Gamma123  = 1          # Bliss independence interaction parameter, drug x1 and x2 and x3 (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Minimum Effect:",
                           "frac12    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin12 = (frac12*EMAXx1 + (1-frac12)*EMAXx2)",
                           "frac13    = 1/(1+(EMAXx1/EMAXx3)^20)",
                           "KillMin13 = (frac13*EMAXx1 + (1-frac13)*EMAXx3)",
                           "frac23    = 1/(1+(EMAXx2/EMAXx3)^20)",
                           "KillMin23 = (frac23*EMAXx2 + (1-frac23)*EMAXx3)",
                           "frac123    = 1/(1+(KillMin12/EMAXx3)^20)",
                           "KillMin123 = (frac123*KillMin12 + (1-frac123)*EMAXx3)",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           "RD33 = Ccx3YPS^hillx3/(EC50x3^hillx3+Ccx3YPS^hillx3) # Ccx3YPS is the concentration of drug x3",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           "Effx3 = RD33",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkillx3 = EMAXx3*Effx3",
                           "Kkill   = Kkillx1 + Kkillx2 + Kkillx3 - Gamma12*Effx1*Effx2*KillMin12 - Gamma13*Effx1*Effx3*KillMin13 - Gamma23*Effx2*Effx3*KillMin23 + Gamma123*Effx1*Effx2*Effx3*KillMin123",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Triple Combo Hybrid Emax Clearance" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PLtot) = (GR - Kkill + Kkillx1 + CLPara)*exp(PLliv-PLtot) - CLPara",
                           "d/dt(PLliv) = GR - Kkill",
                           "PLtot(0)    = PLbase + GR*Tobs0",
                           "PLliv(0)    = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- Drug 3 ---",
                           "EMAXx3  = 0.10       # Maximum clearance rate Drug3 (1/hour)",
                           "EC50x3  = 0.10       # Concentration achieving 50percent of maximum effect Drug3 (ug/mL)",
                           "hillx3  = 1          # Hill coefficient Drug3 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma12   = 1          # Bliss independence interaction parameter, drug x1 and x2 (-)",
                           "Gamma13   = 1          # Bliss independence interaction parameter, drug x1 and x3 (-)",
                           "Gamma23   = 1          # Bliss independence interaction parameter, drug x2 and x3 (-)",
                           "Gamma123  = 1          # Bliss independence interaction parameter, drug x1 and x2 and x3 (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Minimum Effect:",
                           "frac12    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin12 = (frac12*EMAXx1 + (1-frac12)*EMAXx2)",
                           "frac13    = 1/(1+(EMAXx1/EMAXx3)^20)",
                           "KillMin13 = (frac13*EMAXx1 + (1-frac13)*EMAXx3)",
                           "frac23    = 1/(1+(EMAXx2/EMAXx3)^20)",
                           "KillMin23 = (frac23*EMAXx2 + (1-frac23)*EMAXx3)",
                           "frac123    = 1/(1+(KillMin12/EMAXx3)^20)",
                           "KillMin123 = (frac123*KillMin12 + (1-frac123)*EMAXx3)",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           "RD33 = Ccx3YPS^hillx3/(EC50x3^hillx3+Ccx3YPS^hillx3) # Ccx3YPS is the concentration of drug x3",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           "Effx3 = RD33",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkillx3 = EMAXx3*Effx3",
                           "Kkill   = Kkillx1 + Kkillx2 + Kkillx3 - Gamma12*Effx1*Effx2*KillMin12 - Gamma13*Effx1*Effx3*KillMin13 - Gamma23*Effx2*Effx3*KillMin23 + Gamma123*Effx1*Effx2*Effx3*KillMin123",
                           " "), 
                           collapse = "\n"
                         )
                       )
  
  withCure <- case_when(modeltype == "Mono Emax" ~
                       paste0(c(
                         "\n********** MODEL STATES",
                         "# Parasitemia PD model (log transformed parasitemia)",
                         "# Kkill is the killing rate, and may be either a linear or nonlinear function of the drug concentration",
                         "d/dt(PL) = (GR - Kkill - Cure)*Fcure",
                         "PL(0) = PLbase + GR*Tobs0",
                         " ",
                         "********** MODEL PARAMETERS ",
                         "# -------- PD parameters --------",
                         "# --- General ---",
                         "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                         "GR      = 0.05        # Net parasite growth rate (1/hour)",
                         "Tobs0 	= 0           # The time of the first observation relative to the time of the first dose (hours)",
                         "PLcure  = -10         # Log-transformed cure threshold (percent or 1/mL) ",
                         "Hcure   = 5           # Hill coefficient of cure (.)",
                         "mu      = 0.05        # Relative difference between maximum cure rate and growth (.)",
                         "dPLstop = 5           # log-difference between Pcure and Pstop (.)",
                         " ",
                         "********** MODEL VARIABLES ",
                         "# -------- PD --------",
                         "# Cure Rate",
                         "# Cure = CureMAX*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*(CureMAX/GR-1))",
                         "#  		with CureMAX=(1+mu)*GR & Hcure=Hcure",
                         "Cure  = (1+mu)*GR*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*mu)",
                         "Fcure = exp(Hcure*PL)/(exp(Hcure*(PLcure-dPLstop)) + exp(Hcure*PL))",
                         " "), 
                         collapse = "\n"
                       ),
                       modeltype == "Mono Clearance Emax" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate, and may be either a linear or nonlinear function of the drug concentration",
                           "d/dt(PLtot) = (GR*Fcure + CLPara)*exp(PLliv-PLtot) - CLPara",
                           "d/dt(PLliv) = (GR - Kkill - Cure)*Fcure",
                           "PLtot(0)    = PLbase + GR*Tobs0",
                           "PLliv(0)    = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase  = 0           # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0   = 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           "PLcure  = -10         # Log-transformed cure threshold (percent or 1/mL)",
                           "Hcure   = 5           # Hill coefficient of cure (.)",
                           "mu      = 0.05        # Relative difference between maximum cure rate and growth (.)",
                           "dPLstop = 5           # log-difference between Pcure and Pstop (.)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Cure Rate",
                           "# Cure = CureMAX*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PLliv)*(CureMAX/GR-1))",
                           "#  		with CureMAX=(1+mu)*GR & Hcure=Hcure",
                           "Cure  = (1+mu)*GR*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PLliv)*mu)",
                           "Fcure = exp(Hcure*PLliv)/(exp(Hcure*(PLcure-dPLstop)) + exp(Hcure*PLliv))",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Dual Combo Emax" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PL) = (GR - Kkill - Cure)*Fcure",
                           "PL(0) = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0           # The time of the first observation relative to the time of the first dose (hours)",
                           "PLcure  = -10         # Log-transformed cure threshold (percent or 1/mL) ",
                           "Hcure   = 5           # Hill coefficient of cure (.)",
                           "mu      = 0.05        # Relative difference between maximum cure rate and growth (.)",
                           "dPLstop = 5           # log-difference between Pcure and Pstop (.)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma   = 1          # Bliss independence interaction parameter (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Cure Rate",
                           "# Cure = CureMAX*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*(CureMAX/GR-1))",
                           "#  		with CureMAX=(1+mu)*GR & Hcure=Hcure",
                           "Cure  = (1+mu)*GR*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*mu)",
                           "Fcure = exp(Hcure*PL)/(exp(Hcure*(PLcure-dPLstop)) + exp(Hcure*PL))",
                           " ",
                           "# Minimum Effect:",
                           "frac    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin = frac*EMAXx1 + (1-frac)*EMAXx2",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkill   = Kkillx1 + Kkillx2 - Gamma*Effx1*Effx2*KillMin",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Dual Combo Hybrid Emax Clearance" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PLtot) = (GR*Fcure - Kkill + Kkillx1 + CLPara)*exp(PLliv-PLtot) - CLPara",
                           "d/dt(PLliv) = (GR - Kkill - Cure)*Fcure",
                           "PLtot(0)    = PLbase + GR*Tobs0",
                           "PLliv(0)    = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           "PLcure  = -10         # Log-transformed cure threshold (percent or 1/mL) ",
                           "Hcure   = 5           # Hill coefficient of cure (.)",
                           "mu      = 0.05        # Relative difference between maximum cure rate and growth (.)",
                           "dPLstop = 5           # log-difference between Pcure and Pstop (.)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma   = 1          # Bliss independence interaction parameter (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Cure Rate",
                           "# Cure = CureMAX*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*(CureMAX/GR-1))",
                           "#  		with CureMAX=(1+mu)*GR & Hcure=Hcure",
                           "Cure  = (1+mu)*GR*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*mu)",
                           "Fcure = exp(Hcure*PL)/(exp(Hcure*(PLcure-dPLstop)) + exp(Hcure*PL))",
                           " ",
                           "# Minimum Effect:",
                           "frac    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin = frac*EMAXx1 + (1-frac)*EMAXx2",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkill   = Kkillx1 + Kkillx2 - Gamma*Effx1*Effx2*KillMin",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Triple Combo Emax" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PL) = (GR - Kkill - Cure)*Fcure",
                           "PL(0) = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           "PLcure  = -10         # Log-transformed cure threshold (percent or 1/mL) ",
                           "Hcure   = 5           # Hill coefficient of cure (.)",
                           "mu      = 0.05        # Relative difference between maximum cure rate and growth (.)",
                           "dPLstop = 5           # log-difference between Pcure and Pstop (.)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- Drug 3 ---",
                           "EMAXx3  = 0.10       # Maximum clearance rate Drug3 (1/hour)",
                           "EC50x3  = 0.10       # Concentration achieving 50percent of maximum effect Drug3 (ug/mL)",
                           "hillx3  = 1          # Hill coefficient Drug3 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma12   = 1          # Bliss independence interaction parameter, drug x1 and x2 (-)",
                           "Gamma13   = 1          # Bliss independence interaction parameter, drug x1 and x3 (-)",
                           "Gamma23   = 1          # Bliss independence interaction parameter, drug x2 and x3 (-)",
                           "Gamma123  = 1          # Bliss independence interaction parameter, drug x1 and x2 and x3 (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Cure Rate",
                           "# Cure = CureMAX*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*(CureMAX/GR-1))",
                           "#  		with CureMAX=(1+mu)*GR & Hcure=Hcure",
                           "Cure  = (1+mu)*GR*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*mu)",
                           "Fcure = exp(Hcure*PL)/(exp(Hcure*(PLcure-dPLstop)) + exp(Hcure*PL))",
                           " ",
                           "# Minimum Effect:",
                           "frac12    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin12 = (frac12*EMAXx1 + (1-frac12)*EMAXx2)",
                           "frac13    = 1/(1+(EMAXx1/EMAXx3)^20)",
                           "KillMin13 = (frac13*EMAXx1 + (1-frac13)*EMAXx3)",
                           "frac23    = 1/(1+(EMAXx2/EMAXx3)^20)",
                           "KillMin23 = (frac23*EMAXx2 + (1-frac23)*EMAXx3)",
                           "frac123    = 1/(1+(KillMin12/EMAXx3)^20)",
                           "KillMin123 = (frac123*KillMin12 + (1-frac123)*EMAXx3)",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           "RD33 = Ccx3YPS^hillx3/(EC50x3^hillx3+Ccx3YPS^hillx3) # Ccx3YPS is the concentration of drug x3",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           "Effx3 = RD33",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkillx3 = EMAXx3*Effx3",
                           "Kkill   = Kkillx1 + Kkillx2 + Kkillx3 - Gamma12*Effx1*Effx2*KillMin12 - Gamma13*Effx1*Effx3*KillMin13 - Gamma23*Effx2*Effx3*KillMin23 + Gamma123*Effx1*Effx2*Effx3*KillMin123",
                           " "), 
                           collapse = "\n"
                         ),
                       modeltype == "Triple Combo Hybrid Emax Clearance" ~
                         paste0(c(
                           "\n********** MODEL STATES",
                           "# Parasitemia PD model (log transformed parasitemia)",
                           "# Kkill is the killing rate of the drug combination",
                           "d/dt(PLtot) = (GR*Fcure - Kkill + Kkillx1 + CLPara)*exp(PLliv-PLtot) - CLPara",
                           "d/dt(PLliv) = (GR - Kkill - Cure)*Fcure",
                           "PLtot(0)    = PLbase + GR*Tobs0",
                           "PLliv(0)    = PLbase + GR*Tobs0",
                           " ",
                           "********** MODEL PARAMETERS ",
                           "# -------- PD parameters --------",
                           "# --- General ---",
                           "PLbase = 0            # Log-transformed baseline parasitemia (percent or 1/mL)",
                           "GR      = 0.05        # Net parasite growth rate (1/hour)",
                           "Tobs0 	= 0 			    # The time of the first observation relative to the time of the first dose (hours)",
                           "PLcure  = -10         # Log-transformed cure threshold (percent or 1/mL) ",
                           "Hcure   = 5           # Hill coefficient of cure (.)",
                           "mu      = 0.05        # Relative difference between maximum cure rate and growth (.)",
                           "dPLstop = 5           # log-difference between Pcure and Pstop (.)",
                           " ",
                           "# --- Drug 1 ---",
                           "EMAXx1  = 0.10        # Maximum clearance rate Drug1 (1/hour)",
                           "EC50x1  = 0.10        # Concentration achieving 50percent of maximum effect Drug1 (ug/mL)",
                           "hillx1  = 1           # Hill coefficient Drug1 (.)",
                           " ",
                           "# --- Drug 2 ---",
                           "EMAXx2  = 0.10       # Maximum clearance rate Drug2 (1/hour)",
                           "EC50x2  = 0.10       # Concentration achieving 50percent of maximum effect Drug2 (ug/mL)",
                           "hillx2  = 1          # Hill coefficient Drug2 (.)",
                           " ",
                           "# --- Drug 3 ---",
                           "EMAXx3  = 0.10       # Maximum clearance rate Drug3 (1/hour)",
                           "EC50x3  = 0.10       # Concentration achieving 50percent of maximum effect Drug3 (ug/mL)",
                           "hillx3  = 1          # Hill coefficient Drug3 (.)",
                           " ",
                           "# --- PD DDI ---",
                           "# PD interaction parameter",
                           "Gamma12   = 1          # Bliss independence interaction parameter, drug x1 and x2 (-)",
                           "Gamma13   = 1          # Bliss independence interaction parameter, drug x1 and x3 (-)",
                           "Gamma23   = 1          # Bliss independence interaction parameter, drug x2 and x3 (-)",
                           "Gamma123  = 1          # Bliss independence interaction parameter, drug x1 and x2 and x3 (-)",
                           " ",
                           "********** MODEL VARIABLES ",
                           "# -------- PD --------",
                           "# Cure Rate",
                           "# Cure = CureMAX*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*(CureMAX/GR-1))",
                           "#  		with CureMAX=(1+mu)*GR & Hcure=Hcure",
                           "Cure  = (1+mu)*GR*exp(Hcure*PLcure)/(exp(Hcure*PLcure) + exp(Hcure*PL)*mu)",
                           "Fcure = exp(Hcure*PL)/(exp(Hcure*(PLcure-dPLstop)) + exp(Hcure*PL))",
                           " ",
                           "# Minimum Effect:",
                           "frac12    = 1/(1+(EMAXx1/EMAXx2)^20)",
                           "KillMin12 = (frac12*EMAXx1 + (1-frac12)*EMAXx2)",
                           "frac13    = 1/(1+(EMAXx1/EMAXx3)^20)",
                           "KillMin13 = (frac13*EMAXx1 + (1-frac13)*EMAXx3)",
                           "frac23    = 1/(1+(EMAXx2/EMAXx3)^20)",
                           "KillMin23 = (frac23*EMAXx2 + (1-frac23)*EMAXx3)",
                           "frac123    = 1/(1+(KillMin12/EMAXx3)^20)",
                           "KillMin123 = (frac123*KillMin12 + (1-frac123)*EMAXx3)",
                           " ",
                           "# Stimulus Effects:", 
                           "RD11 = Ccx1YPS^hillx1/(EC50x1^hillx1+Ccx1YPS^hillx1) # Ccx1YPS is the concentration of drug x1",
                           "RD22 = Ccx2YPS^hillx2/(EC50x2^hillx2+Ccx2YPS^hillx2) # Ccx2YPS is the concentration of drug x2",
                           "RD33 = Ccx3YPS^hillx3/(EC50x3^hillx3+Ccx3YPS^hillx3) # Ccx3YPS is the concentration of drug x3",
                           " ",
                           "# Effects size:",
                           "Effx1 = RD11",
                           "Effx2 = RD22",
                           "Effx3 = RD33",
                           " ",
                           "# Total Killing (1/hr):",
                           "Kkillx1 = EMAXx1*Effx1",
                           "Kkillx2 = EMAXx2*Effx2",
                           "Kkillx3 = EMAXx3*Effx3",
                           "Kkill   = Kkillx1 + Kkillx2 + Kkillx3 - Gamma12*Effx1*Effx2*KillMin12 - Gamma13*Effx1*Effx3*KillMin13 - Gamma23*Effx2*Effx3*KillMin23 + Gamma123*Effx1*Effx2*Effx3*KillMin123",
                           " "), 
                           collapse = "\n"
                         )
                       )
  cat(crayon:::green("\nSnippet for model without cure function:"), nonCure, 
      crayon:::green("\n\nSnippet for model with cure function:"), withCure)
}

  
  